Make compatible with ruby 2.2
Was getting:

LoadError: cannot load such file -- date/format
/home/jonathan/.rbenv/versions/2.2.1/gemsets/paydici/bundler/gems/runt-e3b6d003d30f/lib/runt.rb:37:in `require'